In [2]:
#imports 
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns

In [3]:
df=pd.read_csv("movies.csv")
print(df.index)
print("All columns are")
ai=0
for i in df:
    print(ai,i)
    ai+=1

RangeIndex(start=0, stop=9742, step=1)
All columns are
0 Id
1 Title
2 Genres

In [4]:
df.shape

(9742, 3)

In [5]:
df.head()

,Id,Title,Genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

In [6]:
df.sample(n=10)

          Id                             Title                  Genres
9296  158842       My Scientology Movie (2016)             Documentary
8403  110387         Unknown Known, The (2013)             Documentary
1261    1676          Starship Troopers (1997)           Action|Sci-Fi
8888  134334            Phir Hera Pheri (2006)                  Comedy
8742  127184                       Eden (2014)                   Drama
363      419   Beverly Hillbillies, The (1993)                  Comedy
5231    8571  Bob & Carol & Ted & Alice (1969)            Comedy|Drama
6376   50064           Good German, The (2006)  Drama|Mystery|Thriller
9231  152372                 Southbound (2016)                  Horror
5115    8143                Lola Montès (1955)                   Drama

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9742 entries, 0 to 9741
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Id      9742 non-null   int64
 1   Title   9742 non-null   object
 2   Genres  9742 non-null   object
dtypes: int64(1), object(2)
memory usage: 228.5+ KB

In [8]:
df.isnull()

         Id  Title  Genres
0     False  False   False
1     False  False   False
2     False  False   False
3     False  False   False
4     False  False   False
...     ...    ...     ...
9737  False  False   False
9738  False  False   False
9739  False  False   False
9740  False  False   False
9741  False  False   False

[9742 rows x 3 columns]

In [9]:
print(df.isnull().sum())
print('Defaulted has 150 null values')

Id        0
Title     0
Genres    0
dtype: int64
Defaulted has 150 null values

In [10]:
df.describe()

                  Id
count    9742.000000
mean    42200.353623
std     52160.494854
min         1.000000
25%      3248.250000
50%      7300.000000
75%     76232.000000
max    193609.000000

In [12]:
df.columns

Index(['Id', 'Title', 'Genres'], dtype='object')